### ISSUE TITLE
ping is reused twice

### ISSUE THREAD

**Issue by willwam845** [RealJammy/The-Jambot#1]
in the readme the ping command is used twice

**Comment by willwam845** [comment]
adding to this, you can probably just remove the commands that an admin can use that a normal can also use

**Comment by willwam845** [comment]
also why cant admins use .github :(

**Comment by RealJammy** [comment]
admins can use all of the commands, i should specify this.

**Comment by RealJammy** [comment]
this has been fixed. thank you for reporting this will
