### ISSUE TITLE
Make a .meme() function in fun

### ISSUE THREAD

**Issue by themonkeyhacker** [RealJammy/The-Jambot#11]
use the reddit api or something to pull a random meme on usage- dw abt api keys and stuff. me and jammy will sort that out. i kinda wanna do this myself but if anyone else feels like giving it a go - leave a comment. happy coding :)

**Comment by ben-sommer** [comment]
https://github.com/RealJammy/The-Jambot/pull/21

**Comment by RealJammy** [comment]
For a non borked version of 21 , #25

**Comment by RealJammy** [comment]
Issue has been fixed by pig
