### ISSUE TITLE
Make .scream work

### ISSUE THREAD

**Issue by RealJammy** [RealJammy/The-Jambot#13]
There is a way to make tts messages, however when I have tried this, it does not work. If you find a way, please may you show me, and even better, make a PR of `.scream`. Thanks!

**Comment by James-261** [comment]
Done it

**Comment by RealJammy** [comment]
Cool,.will test, and if works will close issue. Thanks for your work

**Comment by RealJammy** [comment]
Works, thanks you Pig. Closed.
