### ISSUE TITLE
L69 - L70 of fun.py don't work

### ISSUE THREAD

**Issue by RealJammy** [RealJammy/The-Jambot#18]
After sending a tts message in chat, the following lines are meant to send Benjamin a Direct Message, however does not work. Please may you send a PR and fix this, (this is also a great way to become com dev)

```python
        user = 386245767725056015
        await commands.send_message(user, "fucking sleep ben ffs")
```

**Comment by RealJammy** [comment]
Ben has proposed a solution, have merged, will put live

**Comment by RealJammy** [comment]
didn't work :c

**Comment by ben-sommer** [comment]
idk tbh

**Comment by themonkeyhacker** [comment]
dont use line numbers pls- things can get confusing as they change a lot, justlike reference the function or smthn idk

**Comment by RealJammy** [comment]
ok cool

**Comment by themonkeyhacker** [comment]
I'm confused- do you want an event looking for all tts messages- then on event it does what you described, or are you talking about the one scream function that uses tts?

**Comment by RealJammy** [comment]
cant believe we've gotten to the stage where this is now line 169

**Comment by themonkeyhacker** [comment]
smh fine ill fix it today
