### ISSUE TITLE
Put the 50/50 cog into reddit bcus its not rly that big- also make it get its credentials from the json file

### ISSUE THREAD

**Issue by themonkeyhacker** [RealJammy/The-Jambot#40]
If you put the "fiftyfifty" cog into the reddit cog instead, you won't need to create a new "reddit" object. Instead it will just use the one already existing in the cog. Also classes should begin with capitals uwu.

**Comment by RealJammy** [comment]
The fiftyfifty cog was just a quick test by spec, you've reminded me to delete it, thank you.
Closed.
