### ISSUE TITLE
make reload command exclusive to jammy's id

### ISSUE THREAD

**Issue by themonkeyhacker** [RealJammy/The-Jambot#9]
So rn, all admins can use the reload command, meaning anyone from any serve with admins privs can use this command which could potentially be used to dos the bot ig. just not a good thing to have- which is kinda dumb and i didnt realise at the time (i havent slept in 24 hours gimme a break) if somsone wants to fix this go for it :) just make a pr or dm me if you need help

**Comment by ben-sommer** [comment]
https://github.com/RealJammy/The-Jambot/pull/21/

**Comment by James-261** [comment]
no lol

**Comment by maria-waffle** [comment]
done!

**Comment by themonkeyhacker** [comment]
> done!

Well done! Epic human! <3
